name: Deploy Lambda function to sandbox environment

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambdaFunctionName: misskey-weather-bot-2-sandbox
      ecrRepoName: lambda/misskey-weather-bot-2
    secrets:
      awsDeploymentRoleArn: ${{secrets.AWS_DEPLOYMENT_ROLE_ARN_SANDBOX}}
